{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "86fdcd75",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dicionário 'dicionario_objetivo.json' carregado com sucesso.\n",
      "Dicionário 'dicionario_resgate.json' carregado com sucesso.\n",
      "\n",
      "ERRO ao carregar o Excel. Usando dados de SIMULAÇÃO para demonstração.\n",
      "\n",
      "--- RESULTADO FINAL DO PIPELINE UNIFICADO (Amostra) ---\n",
      "                            input  Valor_Numerico Classificacao_Aporte  \\\n",
      "0  objetivo | Acumular patrimonio             NaN        NÃO SE APLICA   \n",
      "1                        R$ 8.000          8000.0   Regra: Aporte Alto   \n",
      "2                             150           150.0  Regra: Aporte Baixo   \n",
      "3       possiveisResgates | false             NaN        NÃO SE APLICA   \n",
      "\n",
      "                Classificacao_Objetivo  Classificacao_Resgate  \n",
      "0  ACÚMULO DE PATRIMÔNIO / CRESCIMENTO          NÃO SE APLICA  \n",
      "1                        NÃO SE APLICA          NÃO SE APLICA  \n",
      "2                        NÃO SE APLICA          NÃO SE APLICA  \n",
      "3                        NÃO SE APLICA  NÃO PRETENDE RESGATAR  \n",
      "\n",
      "Sucesso! Arquivo 'Case - Wpp_PIPELINE_CLASSIFICADO_final.xlsx' gerado com as três novas colunas de classificação.\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import re\n",
    "import json\n",
    "import sys\n",
    "from fuzzywuzzy import fuzz\n",
    "\n",
    "# ==============================================================================\n",
    "# 1. CONFIGURAÇÃO DO PROJETO E ARQUIVOS DE ENTRADA\n",
    "# ==============================================================================\n",
    "\n",
    "# Caminho do arquivo de dados (Excel)\n",
    "EXCEL_FILE = r'C:\\Users\\ane.freitas\\Downloads\\Case - Wpp (1).xlsx' \n",
    "# Nome da aba/planilha dentro do Excel que será lida\n",
    "SHEET_NAME = 'result' \n",
    "# Nome da coluna que contém o texto de entrada para todas as análises\n",
    "COLUNA_ORIGEM = 'input' \n",
    "\n",
    "# Dicionários (Regras de Negócio) para Classificação Textual\n",
    "DIC_OBJETIVO_FILE = 'dicionario_objetivo.json'\n",
    "DIC_RESGATE_FILE = 'dicionario_resgate.json'\n",
    "# ==============================================================================\n",
    "# 2. FUNÇÕES BASE DE SUPORTE (CARREGAMENTO E CLASSIFICAÇÃO)\n",
    "# ==============================================================================\n",
    "\n",
    "def carregar_dicionario(file_path):\n",
    "    \"\"\"Carrega as Regras de Classificação (dicionários JSON).\"\"\"\n",
    "    try:\n",
    "        with open(file_path, 'r', encoding='utf-8') as f:\n",
    "            data = json.load(f)\n",
    "        \n",
    "        mapping = {}\n",
    "        for categoria, frases_lista in data.items():\n",
    "            for frase in frases_lista:\n",
    "                mapping[frase.lower()] = categoria \n",
    "        \n",
    "        print(f\"Dicionário '{file_path}' carregado com sucesso.\")\n",
    "        return mapping\n",
    "            \n",
    "    except FileNotFoundError:\n",
    "        print(f\"\\nERRO FATAL: O arquivo do dicionário '{file_path}' não foi encontrado.\")\n",
    "        sys.exit(1)\n",
    "\n",
    "# Carrega os dicionários para as análises de Objetivo e Resgate\n",
    "MAPA_OBJETIVOS = carregar_dicionario(DIC_OBJETIVO_FILE)\n",
    "MAPA_RESGATE = carregar_dicionario(DIC_RESGATE_FILE)\n",
    "\n",
    "def classificar_valor_aporte(texto):\n",
    "    \"\"\"\n",
    "    Classificação de Aporte: Extrai o valor (Regex com ajuste para milhar BR) \n",
    "    e aplica as regras de Aporte Baixo/Médio/Alto.\n",
    "    \"\"\"\n",
    "    if pd.isna(texto) or not isinstance(texto, (str, int, float)) or str(texto).strip() == \"\":\n",
    "        return None, 'NÃO SE APLICA'\n",
    "    \n",
    "    texto_limpo = str(texto).lower().strip().replace('r$', '').replace('$', '').replace('reais', '')\n",
    "    \n",
    "    if len(texto_limpo) > 50 or \"http\" in texto_limpo or \"media_\" in texto_limpo:\n",
    "        return None, 'NÃO SE APLICA'\n",
    "\n",
    "    # Lógica de Extração (Regex)\n",
    "    match = re.search(r'(\\d[\\d\\.\\,]*)(\\s*mil|\\s*k)?', texto_limpo)\n",
    "    valor = None\n",
    "    \n",
    "    if match:\n",
    "        valor_str = match.group(1).strip()\n",
    "        multiplicador_str = match.group(2)\n",
    "        limpo = valor_str\n",
    "        \n",
    "        # Lógica para limpar e padronizar o número (ex: '50.000' -> 50000.0)\n",
    "        if ',' in limpo:\n",
    "            limpo = limpo.replace('.', '').replace(',', '.') \n",
    "        else:\n",
    "            partes = limpo.split('.')\n",
    "            if len(partes) > 1 and len(partes[-1]) <= 2:\n",
    "                limpo = \"\".join(partes[:-1]) + \".\" + partes[-1]\n",
    "            else:\n",
    "                limpo = limpo.replace('.', '')\n",
    "\n",
    "        limpo = re.sub(r'[^\\d\\.]', '', limpo)\n",
    "        \n",
    "        try:\n",
    "            valor = float(limpo)\n",
    "            if multiplicador_str and valor < 1000:\n",
    "                valor *= 1000\n",
    "        except ValueError:\n",
    "            valor = None\n",
    "\n",
    "    # Lógica de Classificação (Regras)\n",
    "    if valor is None or valor < 0:\n",
    "        return valor, 'NÃO SE APLICA'\n",
    "    \n",
    "    LIMITE_BAIXO = 1000.00\n",
    "    LIMITE_MEDIO = 5000.00\n",
    "\n",
    "    if valor < LIMITE_BAIXO:\n",
    "        return valor, 'Regra: Aporte Baixo'\n",
    "    elif LIMITE_BAIXO <= valor <= LIMITE_MEDIO:\n",
    "        return valor, 'Regra: Aporte Médio'\n",
    "    elif valor > LIMITE_MEDIO:\n",
    "        return valor, 'Regra: Aporte Alto'\n",
    "    else:\n",
    "        return valor, 'NÃO SE APLICA'\n",
    "\n",
    "def classificar_texto_fuzzy(texto, mapa_dicionario, threshold=80):\n",
    "    \"\"\"\n",
    "    Classificação Textual: Usa Fuzzy Matching (similaridade de texto) para \n",
    "    mapear o input a uma categoria, com retorno padrão unificado para 'NÃO SE APLICA'.\n",
    "    \"\"\"\n",
    "    if pd.isna(texto) or not texto or len(str(texto).strip()) < 2:\n",
    "        return 'NÃO SE APLICA'\n",
    "    \n",
    "    texto_lower = str(texto).lower().strip()\n",
    "    melhor_categoria = 'NÃO SE APLICA' \n",
    "    melhor_score = 0\n",
    "    \n",
    "    for palavra_chave, categoria in mapa_dicionario.items():\n",
    "        \n",
    "        # Força o match exato para metadados (ex: 'possiveisResgates | false')\n",
    "        if palavra_chave.startswith((\"possiveisresgates\", \"objetivo\")):\n",
    "            if palavra_chave in texto_lower:\n",
    "                 return categoria\n",
    "            else:\n",
    "                continue \n",
    "\n",
    "        # Usa Fuzzy Matching para frases de texto livre\n",
    "        score = fuzz.partial_ratio(palavra_chave, texto_lower) \n",
    "        \n",
    "        if score > melhor_score:\n",
    "            melhor_score = score\n",
    "            melhor_categoria = categoria\n",
    "\n",
    "    # Só aceita a classificação se o score for alto o suficiente\n",
    "    if melhor_score >= threshold:\n",
    "        return melhor_categoria\n",
    "    else:\n",
    "        return 'NÃO SE APLICA'\n",
    "    # ==============================================================================\n",
    "# 3. EXECUÇÃO DO PIPELINE DE CLASSIFICAÇÃO COM HIERARQUIA\n",
    "# ==============================================================================\n",
    "\n",
    "try:\n",
    "    # 3.1. Leitura dos dados do Excel\n",
    "    df = pd.read_excel(EXCEL_FILE, sheet_name=SHEET_NAME)\n",
    "    print(f\"\\nDados lidos da aba '{SHEET_NAME}'. Iniciando classificação...\")\n",
    "        \n",
    "except Exception as e:\n",
    "    print(f\"\\nERRO ao carregar o Excel. Usando dados de SIMULAÇÃO para demonstração.\")\n",
    "    # Estrutura de Simulação (caso o Excel não seja encontrado)\n",
    "    data = {COLUNA_ORIGEM: ['objetivo | Acumular patrimonio', 'R$ 8.000', '150', 'possiveisResgates | false']}\n",
    "    df = pd.DataFrame(data)\n",
    "\n",
    "# ------------------------------------------------------------------------------\n",
    "# PASSO 1: CLASSIFICAÇÃO DE VALOR DO APORTE (PRIORIDADE ALTA, INDEPENDENTE)\n",
    "# ------------------------------------------------------------------------------\n",
    "# Cria as colunas 'Valor_Numerico' e 'Classificacao_Aporte'\n",
    "df[['Valor_Numerico', 'Classificacao_Aporte']] = df[COLUNA_ORIGEM].apply(\n",
    "    lambda x: pd.Series(classificar_valor_aporte(x))\n",
    ")\n",
    "# ------------------------------------------------------------------------------\n",
    "# PASSO 2: CLASSIFICAÇÃO DE OBJETIVO DO CLIENTE (PRIORIDADE MÉDIA)\n",
    "# ------------------------------------------------------------------------------\n",
    "# Remove o prefixo 'objetivo | ' para que a classificação seja mais precisa\n",
    "df['Texto_Limpo_Obj'] = (\n",
    "    df[COLUNA_ORIGEM]\n",
    "    .astype(str)\n",
    "    .str.replace(r'^objetivo\\s*\\|\\s*', '', regex=True)\n",
    "    .str.strip()\n",
    ")\n",
    "df['Classificacao_Objetivo'] = df['Texto_Limpo_Obj'].apply(\n",
    "    lambda x: classificar_texto_fuzzy(x, MAPA_OBJETIVOS, threshold=80)\n",
    ")\n",
    "df.drop(columns=['Texto_Limpo_Obj'], inplace=True) # Remove coluna auxiliar de limpeza\n",
    "\n",
    "# ------------------------------------------------------------------------------\n",
    "# PASSO 3: CLASSIFICAÇÃO DE RESGATE (PRIORIDADE BAIXA, CONDICIONAL)\n",
    "# ------------------------------------------------------------------------------\n",
    "# Regra de Hierarquia: Se for classificado como Objetivo (Passo 2), IGNORE a classificação de Resgate.\n",
    "\n",
    "# Condição para um Objetivo ser considerado válido (diferente de 'NÃO SE APLICA')\n",
    "CONDICAO_OBJETIVO_VALIDO = (df['Classificacao_Objetivo'] != 'NÃO SE APLICA')\n",
    "\n",
    "# Função que aplica o Resgate APENAS se o Objetivo não foi identificado\n",
    "def aplicar_classificacao_resgate_condicional(row):\n",
    "    # Verifica a condição de Hierarquia\n",
    "    if CONDICAO_OBJETIVO_VALIDO[row.name]:\n",
    "        return 'NÃO SE APLICA'\n",
    "    # Caso contrário, tenta classificar o Resgate\n",
    "    else:\n",
    "        # Usa um threshold (85) mais alto para ser mais seletivo no Resgate\n",
    "        return classificar_texto_fuzzy(row[COLUNA_ORIGEM], MAPA_RESGATE, threshold=85)\n",
    "\n",
    "df['Classificacao_Resgate'] = df.apply(aplicar_classificacao_resgate_condicional, axis=1)\n",
    "\n",
    "# ==============================================================================\n",
    "# 4. EXPORTAÇÃO DOS RESULTADOS\n",
    "# ==============================================================================\n",
    "\n",
    "# Exibe as colunas relevantes para conferência\n",
    "print(\"\\n--- RESULTADO FINAL DO PIPELINE UNIFICADO (Amostra) ---\")\n",
    "print(df[[COLUNA_ORIGEM, 'Valor_Numerico', 'Classificacao_Aporte', 'Classificacao_Objetivo', 'Classificacao_Resgate']].head(15))\n",
    "\n",
    "# Salva o resultado em um novo arquivo Excel\n",
    "OUTPUT_FILE = 'Case - Wpp_PIPELINE_CLASSIFICADO_final.xlsx'\n",
    "df.to_excel(OUTPUT_FILE, index=False)\n",
    "print(f\"\\nSucesso! Arquivo '{OUTPUT_FILE}' gerado com as três novas colunas de classificação.\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "langchain (3.12.9)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
